{
  "swagger": "2.0",
  "schemes": [
    "http"
  ],
  "host": "demo.waterlinked.com",
  "info": {
    "contact": {
      "x-twitter": "waterlinkedas"
    },
    "description": "API for the Water Linked Underwater GPS. For more details: http://www.waterlinked.com\n\nRecommended approach for connecting to a Underwater GPS via the API is:\n- If \"GET /api/\" times out, the Underwater GPS is not running (on this IP address)\n- If \"GET /api/\" responds with 200 OK check that the api version returrned (eg \"v1\") is supported by the client (eg: also supports \"v1\").\n- If the api version returned does not match what the client supports: give an error to the user and recommend upgrading. (Eg: response is \"v2\" while client only supports \"v1\")\n- If \"GET /api/\" responds with 301 Moved permanently. \"GET /api/v1/version\" to check if the kit has a version earlier than 1.5.\n- \"GET /api/v1/version\" will always respond with 200 OK on Underwater GPS earlier than 1.5 release.\n\nConfiguration API is is not considered stable and will potentially be changed",
    "title": "The Water Linked Underwater GPS",
    "version": "1.0.0",
    "x-apisguru-categories": [
      "location"
    ],
    "x-logo": {
      "url": "https://api.apis.guru/v2/cache/logo/https_twitter.com_waterlinkedas_profile_image.jpeg"
    },
    "x-origin": [
      {
        "format": "swagger",
        "url": "http://demo.waterlinked.com/swagger/swagger.json",
        "version": "2.0"
      }
    ],
    "x-preferred": true,
    "x-providerName": "waterlinked.com"
  },
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "responses": {
    "InternalServerError": {
      "description": "Internal Server Error"
    },
    "NoContent": {
      "description": "No Content"
    },
    "NotFound": {
      "description": "Not Found"
    },
    "OK": {
      "description": "OK"
    }
  },
  "paths": {
    "/api/": {
      "get": {
        "operationId": "about#ApiVersion",
        "produces": [
          "application/vnd.wupdater.apiversion"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/WupdaterApiversion"
            }
          }
        },
        "schemes": [
          "http"
        ],
        "summary": "ApiVersion about",
        "tags": [
          "about"
        ]
      }
    },
    "/api/v1/about": {
      "get": {
        "description": "Get about information",
        "operationId": "about#Get",
        "produces": [
          "application/vnd.waterlinked.about+json"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/WaterlinkedAbout"
            }
          }
        },
        "schemes": [
          "http"
        ],
        "summary": "Get about",
        "tags": [
          "about"
        ]
      }
    },
    "/api/v1/about/status": {
      "get": {
        "description": "Get current IMU and GPS status",
        "operationId": "about#Status",
        "produces": [
          "application/vnd.waterlinked.status+json"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/WaterlinkedStatus"
            }
          }
        },
        "schemes": [
          "http"
        ],
        "summary": "Status about",
        "tags": [
          "about"
        ]
      }
    },
    "/api/v1/about/temperature": {
      "get": {
        "description": "Get board temperature",
        "operationId": "about#Temperature",
        "produces": [
          "application/vnd.waterlinked.temperature+json"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/WaterlinkedTemperature"
            }
          }
        },
        "schemes": [
          "http"
        ],
        "summary": "Temperature about",
        "tags": [
          "about"
        ]
      }
    },
    "/api/v1/config/generic": {
      "get": {
        "description": "Get generic configuration",
        "operationId": "config#Get",
        "produces": [
          "application/vnd.waterlinked.configuration+json"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/WaterlinkedConfiguration"
            }
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "schemes": [
          "http"
        ],
        "summary": "Get config",
        "tags": [
          "config"
        ]
      },
      "put": {
        "description": "Modify generic configuration",
        "operationId": "config#Modify",
        "parameters": [
          {
            "description": "Configuration parameters",
            "in": "body",
            "name": "payload",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ModifyConfigPayload"
            }
          }
        ],
        "produces": [
          "plain/text"
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "schemes": [
          "http"
        ],
        "summary": "Modify config",
        "tags": [
          "config"
        ]
      }
    },
    "/api/v1/config/receivers/": {
      "get": {
        "description": "(Re)Load current receiver settings and return them",
        "operationId": "config#ListReceiver",
        "produces": [
          "application/vnd.waterlinked.receiver+json; type=collection"
        ],
        "responses": {
          "200": {
            "description": "Returned list of receivers",
            "schema": {
              "$ref": "#/definitions/WaterlinkedReceiverCollection"
            }
          }
        },
        "schemes": [
          "http"
        ],
        "summary": "ListReceiver config",
        "tags": [
          "config"
        ]
      }
    },
    "/api/v1/config/receivers/{ID}": {
      "get": {
        "description": "Get receiver configuration by id",
        "operationId": "config#ShowReceiver",
        "parameters": [
          {
            "description": "Identifier",
            "in": "path",
            "name": "ID",
            "required": true,
            "type": "integer"
          }
        ],
        "produces": [
          "application/vnd.waterlinked.receiver+json"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/WaterlinkedReceiver"
            }
          },
          "404": {
            "description": "Not Found"
          }
        },
        "schemes": [
          "http"
        ],
        "summary": "ShowReceiver config",
        "tags": [
          "config"
        ]
      },
      "put": {
        "description": "Modify receiver configuration, does not apply the change until generic modify is called. Calling list will discard changes",
        "operationId": "config#ModifyReceiver",
        "parameters": [
          {
            "description": "Identifier",
            "in": "path",
            "name": "ID",
            "required": true,
            "type": "integer"
          },
          {
            "description": "A receiver configuration",
            "in": "body",
            "name": "payload",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ModifyReceiverConfigPayload"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "No Content"
          },
          "404": {
            "description": "Not Found"
          }
        },
        "schemes": [
          "http"
        ],
        "summary": "ModifyReceiver config",
        "tags": [
          "config"
        ]
      }
    },
    "/api/v1/external/depth": {
      "put": {
        "description": "Set depth from external source. If Locator A1 is used, this is required to get a position",
        "operationId": "external#SetDepth",
        "parameters": [
          {
            "description": "Current locator depth and temperature",
            "in": "body",
            "name": "payload",
            "required": true,
            "schema": {
              "$ref": "#/definitions/SetDepthExternalPayload"
            }
          }
        ],
        "produces": [
          "text/plain"
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "schemes": [
          "http"
        ],
        "summary": "SetDepth external",
        "tags": [
          "external"
        ]
      }
    },
    "/api/v1/external/master": {
      "put": {
        "description": "Set current global position of master electronics from external source. Values are only used if GPS mode is set to use external GPS",
        "operationId": "external#SetMaster",
        "parameters": [
          {
            "description": "Global master position from external source",
            "in": "body",
            "name": "payload",
            "required": true,
            "schema": {
              "$ref": "#/definitions/SetMasterExternalPayload"
            }
          }
        ],
        "produces": [
          "text/plain"
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "schemes": [
          "http"
        ],
        "summary": "SetMaster external",
        "tags": [
          "external"
        ]
      }
    },
    "/api/v1/external/orientation": {
      "get": {
        "description": "Get orientation of ROV/Locator set by external",
        "operationId": "external#GetOrientation",
        "produces": [
          "application/vnd.wl.external.locator.orientation+json"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/WlExternalLocatorOrientation"
            }
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "schemes": [
          "http"
        ],
        "summary": "GetOrientation external",
        "tags": [
          "external"
        ]
      },
      "put": {
        "description": "Set orientation/compass heading of ROV/Locator. This is used only for visualization in GUI",
        "operationId": "external#SetOrientation",
        "parameters": [
          {
            "description": "Set current compass heading of ROV/locator",
            "in": "body",
            "name": "payload",
            "required": true,
            "schema": {
              "$ref": "#/definitions/SetOrientationExternalPayload"
            }
          }
        ],
        "produces": [
          "text/plain"
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "schemes": [
          "http"
        ],
        "summary": "SetOrientation external",
        "tags": [
          "external"
        ]
      }
    },
    "/api/v1/position/acoustic/filtered": {
      "get": {
        "description": "Get current Kalman filtered acoustic position relative to master acoustics. Expected update frequency: 4 Hz",
        "operationId": "position#AcousticFiltered",
        "produces": [
          "application/vnd.waterlinked.accoustic.position+json"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/WaterlinkedAccousticPosition"
            }
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "schemes": [
          "http"
        ],
        "summary": "AcousticFiltered position",
        "tags": [
          "position"
        ]
      }
    },
    "/api/v1/position/acoustic/raw": {
      "get": {
        "description": "Get current unfiltered acoustic position relative to master acoustics. Expected update frequency: 4 Hz",
        "operationId": "position#AcousticRaw",
        "produces": [
          "application/vnd.waterlinked.accoustic.position+json"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/WaterlinkedAccousticPosition"
            }
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "schemes": [
          "http"
        ],
        "summary": "AcousticRaw position",
        "tags": [
          "position"
        ]
      }
    },
    "/api/v1/position/global": {
      "get": {
        "description": "Get current global position of locator. Locator position is calculated from the current acoustic position and the global position of the master electronics. Expected update frequency: 4 Hz",
        "operationId": "position#Get",
        "produces": [
          "application/vnd.wl.global.position+json"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/WlGlobalPosition"
            }
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "schemes": [
          "http"
        ],
        "summary": "Get position",
        "tags": [
          "position"
        ]
      }
    },
    "/api/v1/position/master": {
      "get": {
        "description": "Get current global position of master electronics. Expected update frequency: 1 Hz",
        "operationId": "position#GetMaster",
        "produces": [
          "application/vnd.wl.master.position+json"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/WlMasterPosition"
            }
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "schemes": [
          "http"
        ],
        "summary": "GetMaster position",
        "tags": [
          "position"
        ]
      }
    }
  },
  "definitions": {
    "ModifyConfigPayload": {
      "description": "Configuration parameters",
      "example": {
        "carrier_frequency": 150,
        "compass": "static",
        "gps": "external",
        "range_max_x": 50,
        "range_max_y": 50,
        "range_max_z": 50,
        "range_min_x": 50,
        "range_min_y": 50,
        "static_lat": 63.422,
        "static_lon": 10.424,
        "static_orientation": 42,
        "use_external_depth": false
      },
      "properties": {
        "carrier_frequency": {
          "description": "Carrier frequency (kHz)",
          "example": 150,
          "maximum": 200,
          "minimum": 100,
          "type": "number"
        },
        "compass": {
          "description": "Compass provider setting",
          "enum": [
            "onboard",
            "static",
            "external"
          ],
          "example": "static",
          "type": "string"
        },
        "gps": {
          "description": "GPS provider setting",
          "enum": [
            "onboard",
            "static",
            "external"
          ],
          "example": "external",
          "type": "string"
        },
        "range_max_x": {
          "description": "Max range (meters)",
          "example": 50,
          "maximum": 100,
          "minimum": 0,
          "type": "number"
        },
        "range_max_y": {
          "description": "Max range (meters)",
          "example": 50,
          "maximum": 100,
          "minimum": 0,
          "type": "number"
        },
        "range_max_z": {
          "description": "Max range (meters)",
          "example": 50,
          "maximum": 100,
          "minimum": 1,
          "type": "number"
        },
        "range_min_x": {
          "description": "Max range (meters)",
          "example": 50,
          "maximum": 0,
          "minimum": -100,
          "type": "number"
        },
        "range_min_y": {
          "description": "Max range (meters)",
          "example": 50,
          "maximum": 0,
          "minimum": -100,
          "type": "number"
        },
        "static_lat": {
          "description": "Latitude to use in static mode",
          "example": 63.422,
          "maximum": 90,
          "minimum": -90,
          "type": "number"
        },
        "static_lon": {
          "description": "Longitude to use in static mode",
          "example": 10.424,
          "maximum": 180,
          "minimum": -180,
          "type": "number"
        },
        "static_orientation": {
          "description": "Orientation/compass reading to use in static mode (degrees)",
          "example": 42,
          "maximum": 359,
          "minimum": 0,
          "type": "number"
        },
        "use_external_depth": {
          "description": "Use external depth. Required to be true when using Locator-A1.",
          "example": false,
          "type": "boolean"
        }
      },
      "required": [
        "carrier_frequency",
        "range_min_x",
        "range_max_x",
        "range_min_y",
        "range_max_y",
        "range_max_z",
        "use_external_depth",
        "gps",
        "compass",
        "static_lat",
        "static_lon",
        "static_orientation"
      ],
      "title": "ModifyConfigPayload",
      "type": "object"
    },
    "ModifyReceiverConfigPayload": {
      "description": "A receiver configuration",
      "example": {
        "id": 3143803153813247500,
        "x": 0.748659470979663,
        "y": 0.5191780885101608,
        "z": 0.8800592996534627
      },
      "properties": {
        "id": {
          "description": "Unique receiver identifier",
          "example": 3143803153813247500,
          "format": "int64",
          "type": "integer"
        },
        "x": {
          "description": "Configured X position relative to master electronics (meter)",
          "example": 0.748659470979663,
          "format": "double",
          "type": "number"
        },
        "y": {
          "description": "Configured Y position relative to master electronics (meter)",
          "example": 0.5191780885101608,
          "format": "double",
          "type": "number"
        },
        "z": {
          "description": "Configured Z position relative to master electronics (meter)",
          "example": 0.8800592996534627,
          "format": "double",
          "type": "number"
        }
      },
      "required": [
        "id",
        "x",
        "y",
        "z"
      ],
      "title": "ModifyReceiverConfigPayload",
      "type": "object"
    },
    "SetDepthExternalPayload": {
      "description": "Current locator depth and temperature",
      "example": {
        "depth": 3.2,
        "temp": 11.2
      },
      "properties": {
        "depth": {
          "description": "Curent depth (meter)",
          "example": 3.2,
          "maximum": 100,
          "minimum": 0,
          "type": "number"
        },
        "temp": {
          "description": "Current water temperature (C)",
          "example": 11.2,
          "maximum": 60,
          "minimum": -10,
          "type": "number"
        }
      },
      "required": [
        "depth",
        "temp"
      ],
      "title": "SetDepthExternalPayload",
      "type": "object"
    },
    "SetMasterExternalPayload": {
      "description": "Global master position from external source",
      "example": {
        "lat": 63.422,
        "lon": 10.424,
        "orientation": 42
      },
      "properties": {
        "lat": {
          "description": "Current Latitude",
          "example": 63.422,
          "maximum": 90,
          "minimum": -90,
          "type": "number"
        },
        "lon": {
          "description": "Current Longitude",
          "example": 10.424,
          "maximum": 180,
          "minimum": -180,
          "type": "number"
        },
        "orientation": {
          "description": "Current orientation/compass heading (degrees)",
          "example": 42,
          "maximum": 359,
          "minimum": 0,
          "type": "number"
        }
      },
      "required": [
        "lat",
        "lon",
        "orientation"
      ],
      "title": "SetMasterExternalPayload",
      "type": "object"
    },
    "SetOrientationExternalPayload": {
      "description": "Set current compass heading of ROV/locator",
      "example": {
        "orientation": 42
      },
      "properties": {
        "orientation": {
          "description": "Current orientation/compass heading (degrees). -1 means no orientation set",
          "example": 42,
          "maximum": 359,
          "minimum": -1,
          "type": "number"
        }
      },
      "required": [
        "orientation"
      ],
      "title": "SetOrientationExternalPayload",
      "type": "object"
    },
    "WaterlinkedAbout": {
      "description": "About information (default view)",
      "example": {
        "chipid": "0x123456789",
        "version": "1.0.0 (abc.def)"
      },
      "properties": {
        "chipid": {
          "description": "Chip identifier",
          "example": "0x123456789",
          "type": "string"
        },
        "version": {
          "description": "Web Server version string",
          "example": "1.0.0 (abc.def)",
          "type": "string"
        }
      },
      "required": [
        "version",
        "chipid"
      ],
      "title": "Mediatype identifier: application/vnd.waterlinked.about+json; view=default",
      "type": "object"
    },
    "WaterlinkedAccousticPosition": {
      "description": "Current relative Locator position (default view)",
      "example": {
        "std": 0.5,
        "temp": 5.5,
        "x": 32.1,
        "y": 11.2,
        "z": 10.2
      },
      "properties": {
        "std": {
          "description": "Current accoustic position accuracy (meter)",
          "example": 0.5,
          "minimum": 0,
          "type": "number"
        },
        "temp": {
          "description": "Current accoustic temperature (C)",
          "example": 5.5,
          "format": "double",
          "type": "number"
        },
        "x": {
          "description": "Current accoustic x position relative to master electronics (meter)",
          "example": 32.1,
          "format": "double",
          "type": "number"
        },
        "y": {
          "description": "Current accoustic y position relative to master electronics (meter)",
          "example": 11.2,
          "format": "double",
          "type": "number"
        },
        "z": {
          "description": "Current accoustic z position (depth) relative to master electronics (meter)",
          "example": 10.2,
          "minimum": 0,
          "type": "number"
        }
      },
      "required": [
        "x",
        "y",
        "z",
        "std",
        "temp"
      ],
      "title": "Mediatype identifier: application/vnd.waterlinked.accoustic.position+json; view=default",
      "type": "object"
    },
    "WaterlinkedConfiguration": {
      "description": "Configuration parameters (default view)",
      "example": {
        "carrier_frequency": 150,
        "compass": "static",
        "gps": "external",
        "range_max_x": 50,
        "range_max_y": 50,
        "range_max_z": 50,
        "range_min_x": 50,
        "range_min_y": 50,
        "static_lat": 63.422,
        "static_lon": 10.424,
        "static_orientation": 42,
        "use_external_depth": false
      },
      "properties": {
        "carrier_frequency": {
          "description": "Carrier frequency (kHz)",
          "example": 150,
          "maximum": 200,
          "minimum": 100,
          "type": "number"
        },
        "compass": {
          "description": "Compass provider setting",
          "enum": [
            "onboard",
            "static",
            "external"
          ],
          "example": "static",
          "type": "string"
        },
        "gps": {
          "description": "GPS provider setting",
          "enum": [
            "onboard",
            "static",
            "external"
          ],
          "example": "external",
          "type": "string"
        },
        "range_max_x": {
          "description": "Max range (meters)",
          "example": 50,
          "maximum": 100,
          "minimum": 0,
          "type": "number"
        },
        "range_max_y": {
          "description": "Max range (meters)",
          "example": 50,
          "maximum": 100,
          "minimum": 0,
          "type": "number"
        },
        "range_max_z": {
          "description": "Max range (meters)",
          "example": 50,
          "maximum": 100,
          "minimum": 1,
          "type": "number"
        },
        "range_min_x": {
          "description": "Max range (meters)",
          "example": 50,
          "maximum": 0,
          "minimum": -100,
          "type": "number"
        },
        "range_min_y": {
          "description": "Max range (meters)",
          "example": 50,
          "maximum": 0,
          "minimum": -100,
          "type": "number"
        },
        "static_lat": {
          "description": "Latitude to use in static mode",
          "example": 63.422,
          "maximum": 90,
          "minimum": -90,
          "type": "number"
        },
        "static_lon": {
          "description": "Longitude to use in static mode",
          "example": 10.424,
          "maximum": 180,
          "minimum": -180,
          "type": "number"
        },
        "static_orientation": {
          "description": "Orientation/compass reading to use in static mode (degrees)",
          "example": 42,
          "maximum": 359,
          "minimum": 0,
          "type": "number"
        },
        "use_external_depth": {
          "description": "Use external depth. Required to be true when using Locator-A1.",
          "example": false,
          "type": "boolean"
        }
      },
      "required": [
        "carrier_frequency",
        "range_min_x",
        "range_max_x",
        "range_min_y",
        "range_max_y",
        "range_max_z",
        "use_external_depth",
        "gps",
        "compass",
        "static_lat",
        "static_lon",
        "static_orientation"
      ],
      "title": "Mediatype identifier: application/vnd.waterlinked.configuration+json; view=default",
      "type": "object"
    },
    "WaterlinkedReceiver": {
      "description": "A receiver configuration (default view)",
      "example": {
        "id": 3143803153813247500,
        "x": 0.748659470979663,
        "y": 0.5191780885101608,
        "z": 0.8800592996534627
      },
      "properties": {
        "id": {
          "description": "Unique receiver identifier",
          "example": 3143803153813247500,
          "format": "int64",
          "type": "integer"
        },
        "x": {
          "description": "Configured X position relative to master electronics (meter)",
          "example": 0.748659470979663,
          "format": "double",
          "type": "number"
        },
        "y": {
          "description": "Configured Y position relative to master electronics (meter)",
          "example": 0.5191780885101608,
          "format": "double",
          "type": "number"
        },
        "z": {
          "description": "Configured Z position relative to master electronics (meter)",
          "example": 0.8800592996534627,
          "format": "double",
          "type": "number"
        }
      },
      "required": [
        "id",
        "x",
        "y",
        "z"
      ],
      "title": "Mediatype identifier: application/vnd.waterlinked.receiver+json; view=default",
      "type": "object"
    },
    "WaterlinkedReceiverCollection": {
      "description": "WaterlinkedReceiverCollection is the media type for an array of WaterlinkedReceiver (default view)",
      "example": [
        {
          "id": 3143803153813247500,
          "x": 0.748659470979663,
          "y": 0.5191780885101608,
          "z": 0.8800592996534627
        },
        {
          "id": 3143803153813247500,
          "x": 0.748659470979663,
          "y": 0.5191780885101608,
          "z": 0.8800592996534627
        },
        {
          "id": 3143803153813247500,
          "x": 0.748659470979663,
          "y": 0.5191780885101608,
          "z": 0.8800592996534627
        }
      ],
      "items": {
        "$ref": "#/definitions/WaterlinkedReceiver"
      },
      "title": "Mediatype identifier: application/vnd.waterlinked.receiver+json; type=collection; view=default",
      "type": "array"
    },
    "WaterlinkedStatus": {
      "description": "Status information (default view)",
      "example": {
        "gps": 2,
        "imu": 2
      },
      "properties": {
        "gps": {
          "description": "GPS lock status",
          "example": 2,
          "maximum": 3,
          "minimum": 0,
          "type": "integer"
        },
        "imu": {
          "description": "IMU calibration status",
          "example": 2,
          "maximum": 3,
          "minimum": 0,
          "type": "integer"
        }
      },
      "required": [
        "imu",
        "gps"
      ],
      "title": "Mediatype identifier: application/vnd.waterlinked.status+json; view=default",
      "type": "object"
    },
    "WaterlinkedTemperature": {
      "description": "Temperature information (default view)",
      "example": {
        "board": 37
      },
      "properties": {
        "board": {
          "description": "Board temperature (C)",
          "example": 37,
          "format": "double",
          "type": "number"
        }
      },
      "required": [
        "board"
      ],
      "title": "Mediatype identifier: application/vnd.waterlinked.temperature+json; view=default",
      "type": "object"
    },
    "WlExternalLocatorOrientation": {
      "description": "Set current compass heading of ROV/locator (default view)",
      "example": {
        "orientation": 42
      },
      "properties": {
        "orientation": {
          "description": "Current orientation/compass heading (degrees). -1 means no orientation set",
          "example": 42,
          "maximum": 359,
          "minimum": -1,
          "type": "number"
        }
      },
      "required": [
        "orientation"
      ],
      "title": "Mediatype identifier: application/vnd.wl.external.locator.orientation+json; view=default",
      "type": "object"
    },
    "WlGlobalPosition": {
      "description": "Global locator position (default view)",
      "example": {
        "lat": 63.422,
        "lon": 10.424
      },
      "properties": {
        "lat": {
          "description": "Current Latitude",
          "example": 63.422,
          "maximum": 90,
          "minimum": -90,
          "type": "number"
        },
        "lon": {
          "description": "Current Longitude",
          "example": 10.424,
          "maximum": 180,
          "minimum": -180,
          "type": "number"
        }
      },
      "required": [
        "lat",
        "lon"
      ],
      "title": "Mediatype identifier: application/vnd.wl.global.position+json; view=default",
      "type": "object"
    },
    "WlMasterPosition": {
      "description": "GPS and IMU position (default view)",
      "example": {
        "cog": 42,
        "hdop": 1.9,
        "lat": 63.422,
        "lon": 10.424,
        "numsats": 11,
        "orientation": 42,
        "sog": 0.5
      },
      "properties": {
        "cog": {
          "description": "Course over ground (degrees). -1 means no data.",
          "example": 42,
          "maximum": 359,
          "minimum": -1,
          "type": "number"
        },
        "hdop": {
          "description": "Horizontal dilution of precision. -1 means no data.",
          "example": 1.9,
          "minimum": -1,
          "type": "number"
        },
        "lat": {
          "description": "Current Latitude",
          "example": 63.422,
          "maximum": 90,
          "minimum": -90,
          "type": "number"
        },
        "lon": {
          "description": "Current Longitude",
          "example": 10.424,
          "maximum": 180,
          "minimum": -180,
          "type": "number"
        },
        "numsats": {
          "description": "Number of satellites. -1 means no data.",
          "example": 11,
          "minimum": -1,
          "type": "number"
        },
        "orientation": {
          "description": "Current orientation/compass heading (degrees). -1 means no data.",
          "example": 42,
          "maximum": 359,
          "minimum": -1,
          "type": "number"
        },
        "sog": {
          "description": "Speed over ground (km/h). -1 means no data.",
          "example": 0.5,
          "minimum": -1,
          "type": "number"
        }
      },
      "required": [
        "lat",
        "lon",
        "orientation",
        "cog",
        "sog",
        "hdop",
        "numsats"
      ],
      "title": "Mediatype identifier: application/vnd.wl.master.position+json; view=default",
      "type": "object"
    },
    "WupdaterApiversion": {
      "description": "Returns supported api versions (default view)",
      "example": {
        "versions": [
          "v1",
          "v2"
        ]
      },
      "properties": {
        "versions": {
          "description": "Supported api versions",
          "example": [
            "v1",
            "v2"
          ],
          "items": {
            "example": "Sequi fugit quis vero in deleniti.",
            "type": "string"
          },
          "type": "array"
        }
      },
      "required": [
        "versions"
      ],
      "title": "Mediatype identifier: application/vnd.wupdater.apiversion; view=default",
      "type": "object"
    }
  }
}
